### ISSUE TITLE
Case-sensitive search issue in Cyrillic

### ISSUE THREAD

**Issue by ghost** [PontusHorn/Pico-Search#7]
Dear Pontus, it's me again :) 

I have some issue with search on Cyrillic (all in UTF-8). When I do search in Latin - it works great and case **in**sensitive. But in Cyrillic, I see different results:

![1](https://user-images.githubusercontent.com/7046304/62820880-a24b7c80-bb73-11e9-8235-dae5928c8280.png)

![2](https://user-images.githubusercontent.com/7046304/62820882-a5df0380-bb73-11e9-9e52-9ae4a55ac2ed.png)

As you may see capitalize **T** doesn't equal lowercase **т** .

**Comment by ghost** [comment]
Looks like it's about _u_ flag in _preg_match_ , but I don't know how to make this regular expression and check it :)

**Comment by PontusHorn** [comment]
Hey, thanks for the report! Fixed this in 76e9bab. Let me know if it works as expected?

**Comment by ghost** [comment]
it works! many thanks
