### ISSUE TITLE
fix: server throws "undefined variable" errors for $folder and $searchTerm

### ISSUE THREAD

**Issue by cfreitag** [PontusHorn/Pico-Search#8]
In line 67, it is possible that `$folder` is undefinded if the variable `search_area` isn't set and the `if` clause in line 62 is never entered. To prevent this, define `$folder = array();` before it is first used, e. g. after line 57.

In line 171 the variable passed to public function `isLowValueWord` should be `$searchTerm`, not `$word` for the function to work.

See revised version of plugin attached.

[40-PicoSearch-revised.php.txt](https://github.com/PontusHorn/Pico-Search/files/3783658/40-PicoSearch-revised.php.txt)

**Comment by PontusHorn** [comment]
Thanks for the heads-up. Fixed in 4476f858865306377e13cf820f0b89eabcbc6fc8 and b539f8e3596e6048aac9fee534565b91a2f505c3.
